shopify_assessment:
  target: staging
  outputs:
    staging:
      type: postgres
      host: "{{ env_var('DBT_STAGING_HOST') }}"
      user: "{{ env_var('DBT_STAGING_USER') }}"
      password: "{{ env_var('DBT_STAGING_PASSWORD') }}"
      port: "{{ env_var('DBT_STAGING_PORT') | int }}"
      dbname: "{{ env_var('DBT_STAGING_DB') }}"
      schema: staging
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('DBT_PROD_HOST') }}"
      user: "{{ env_var('DBT_PROD_USER') }}"
      password: "{{ env_var('DBT_PROD_PASSWORD') }}"
      port: "{{ env_var('DBT_PROD_PORT') | int }}"
      dbname: "{{ env_var('DBT_PROD_DB') }}"
      schema: marts
      threads: 4